name: Android Anime CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: set up gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update local.properties
        env:
          url_graphql=${{ secrets.URL_GRAPHQL }}
          name_database=${{ secrets.NAME_DATABASE }}
          split_io_key=${{ secrets.SPLIT_IO_KEY }}
          feature_flag=${{ secrets.FEATURE_FLAG }}
      - name: Execute validations
        run: ./gradlew executeValidations

      - name: Build App
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
