name: Android Anime CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean Gradle Cache
        run: ./gradlew clean
      - name: Execute validations
        run: ./gradlew executeValidations
      - name: Build App
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi